### ISSUE TITLE
No text in windows App

### ISSUE THREAD

**Issue by tomaswilhelmsson** [scriptBoris/DataGridSam#1]
Building a cross platform app (Windows, Android) and tried getting this addon working.
Been at it for hours and no text showing in the table .. so started the android version and it worked fine!

Version 1.1.2 installed with NuGet

![bugs](https://user-images.githubusercontent.com/35802104/75072282-80a25900-54f7-11ea-905d-a3ba2486d728.png)

**Comment by tomaswilhelmsson** [comment]
Ah i made an UWP app insted and now it work, the app i had was WPF.
Is it hard to make it work in WPF also ? =)

**Comment by scriptBoris** [comment]
@tomaswilhelmsson I’m not sure about the WPF, maybe it will be realized in the future
