### ISSUE TITLE
Inserting data from embedded objects

### ISSUE THREAD

**Issue by alzaburetz** [scriptBoris/DataGridSam#2]
Is it possible to insert data from embedded object into the table. For example, I have a class
```
public class Vihecle
{
     public string Name {get; set;}
     public Engine Engine {get; set;}
     ...
}

public class Engine
{
     public float Volume {get; set;}
     public int HorsePower {get; set;}
     public string SerialNumber {get; set;}
}
```
Is it possible to get data from Engine field into the table? Will ```PropertyName="Engine.Volume"``` work?

**Comment by scriptBoris** [comment]
Hi, in a Sample project, I created a new ViewModel (Embedded demo) and found that it works.
However, it is necessary to conduct tests of how this will work with RowTriggers

![image](https://user-images.githubusercontent.com/29772096/77024737-4c249e80-69ca-11ea-8b1e-2a9bbbc12f70.png)

**Comment by scriptBoris** [comment]
You can clone this repository and run Sample project for testing.
Do not forget to switch the Dev branch
