### ISSUE TITLE
Grouping

### ISSUE THREAD

**Issue by sudfunk** [scriptBoris/DataGridSam#3]
can  SamDataGrid   **Grouping Data** ? , if it can please give me an example !
Thanks.

**Comment by scriptBoris** [comment]
> can SamDataGrid **Grouping Data** ? , if it can please give me an example !
> Thanks.

Sorry, but DataGridSam can't grouping data. Maybe sometime i add grouping data functional

**Comment by sudfunk** [comment]
Oh.. , Okay .., any idea for the groupinjg data , Thanks

**Comment by sudfunk** [comment]
Thanks
